### ISSUE TITLE
No sé bien usar los diferentes tipos de Layout para posicionar los componentes ):

### ISSUE THREAD

**Issue by AnaAIHS** [AnaAIHS/Cajero#1]
@emmanuel789

**Comment by emmanuel789** [comment]
@AnaAIHS hola Ana bueno primero debes conocer los tipos de layouts que existen checa este tutorial http://javax-peru.blogspot.mx/2008/11/clases-de-distribucin-de-objetos.html  y si tienes problemas me avisas saludos
